---
title: "Tugas 3 Komputasi Statistik"
author: "Nathan Julyan Putra Deshwara"
date: "2026-09-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Tugas

1. Buka data airquality

2. Buat histogram untuk variabel Wind, sertakan pula density nya

3. Buat boxplot dan steam and leaf

4. Buat scatter plot

### Jawab

1. Membuka data airquality
```{r}
airquality
```

2. Membuat histogram untuk variabel wind serta densitynya
```{r}
dens <- density(airquality$Wind)

hist(airquality$Wind,
     probability = TRUE,
     main = "Histogram Kecepatan Angin", 
     xlab = "Wind (mph)", 
     col = "skyblue")

lines(dens, col = "blue", lwd = 2)
```

3. Membuat boxplot dan steam leaf
Boxplot
```{r}
boxplot(airquality$Wind,
        horizontal = TRUE,
        main = "Boxplot Wind",
        xlab = "Wind")
```

Steam and Leaf
```{r}
stem(airquality$Wind)
```

4. Membuat scatter plot
```{r}
plot(Temp ~ Wind,
     data = airquality,
     main = "Scatter Plot Wind vs Temperature",
     xlab = "Wind",
     ylab = "Temperature",
     pch = 16)

rug(airquality$Wind)            
rug(airquality$Temp,side = 2)


abline(lm(Temp ~ Wind, data = airquality), col = "red", lwd = 2, lty = 2)
```